######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 27 15:17:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
HEADERS += mytext.h
SOURCES += main.cpp \
           mytext.cpp \
           src/gridlayout.cpp \
           src/hello1.cpp \
           src/hello_world.cpp
