# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuto', '0002_auto_20160413_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmithBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookAuto.Author')),
            ],
        ),
    ]
