# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuto', '0004_auto_20160413_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smithbook',
            name='author',
        ),
        migrations.AddField(
            model_name='smithbook',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BookAuto.Author'),
            preserve_default=False,
        ),
    ]
