# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuto', '0006_auto_20160414_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('middle', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last', 'first', 'middle'],
                'verbose_name_plural': 'people',
            },
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('first', 'last', 'middle')]),
        ),
    ]
