# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuto', '0007_auto_20160414_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.TextField(default=1, verbose_name='\u6e56\u5357'),
            preserve_default=False,
        ),
    ]
