# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAuto', '0008_author_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.TextField(),
        ),
    ]
