# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this physical testbed', max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('owner', models.EmailField(help_text='Address for reporting testbed problems.', max_length=254, verbose_name='Owner Email')),
                ('resultdist', models.EmailField(help_text='Default address for emailing batch results', max_length=254, verbose_name='Results Email')),
                ('description', models.TextField(blank=True)),
                ('config', models.TextField(blank=True, help_text='Basic testbed configuration parameters (e.g. DUT IP address) as a python dictionary string')),
            ],
        ),
        migrations.CreateModel(
            name='TestbedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the python class that implements this type of testbed', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this testbed and description of all configuration parameters')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='testbed',
            name='tbtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auto.TestbedType'),
        ),
    ]
