# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestbedComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this component and the python class that implements it', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this component.')),
                ('config', models.TextField(blank=True, help_text='Basic testbed component configuration parameters (e.g. DUT IP address) as a python dictionary string')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
