# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0003_auto_20160412_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutotestConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastbuildnum', models.IntegerField(default=0, help_text='Last build number autotested; Only test new builds greater than this.')),
                ('seq', models.IntegerField(default=0, help_text='Specifies priority of this build_stream if multiple build streams have new builds available')),
                ('DUT', models.ForeignKey(blank=True, help_text='The testbed component under test (if testbed has multiple potential DUTS)', null=True, on_delete=django.db.models.deletion.CASCADE, to='Auto.TestbedComponent')),
                ('build_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auto.BuildStream')),
                ('suites', models.ManyToManyField(help_text='list of test suites to run for this batch', null=True, to='Auto.TestSuite')),
                ('testbed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auto.Testbed')),
            ],
            options={
                'ordering': ('seq',),
            },
        ),
    ]
