######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 27 15:22:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello1.cpp
