# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='\u6d4b\u8bd5\u7528\u4f8b\u7684\u540d\u5b57', max_length=60)),
                ('test_params', models.TextField(blank=True, help_text='\u6d4b\u8bd5\u4f20\u9012\u7684\u53c2\u6570\uff0c\u7528\u6237\u540d\u548c\u5bc6\u7801')),
                ('seq', models.IntegerField(help_text='Relative ordering of this test case within the test suite')),
                ('common_name', models.CharField(blank=True, help_text='Common name for this test', max_length=120)),
                ('enabled', models.BooleanField(default=True, help_text='Will not copied to TestRun if disabled')),
                ('exc_level', models.IntegerField(default=0, help_text='test case execution level. Test runner, qarun uses it to decide what to do if this test FAIL/ERROR')),
                ('is_cleanup', models.BooleanField(default=False, help_text='Is a cleanup test case?')),
            ],
            options={
                'ordering': ('seq',),
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.TextField(blank=True, help_text='Text dictionary of testbed component configs to use for this test suite')),
                ('xtype', models.CharField(blank=True, choices=[('', 'Regression Tests'), ('combo', 'Combination/Composition Tests')], help_text='execution type of this test suite. Default is regression test.', max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.TestSuite'),
        ),
    ]
