######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 29 15:04:57 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt3.cpp
