# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='please enter you Issue title', max_length=100)),
                ('discription', models.TextField(blank=True, help_text='enter you issue discription')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': '\u95ee\u9898\u63cf\u8ff0',
            },
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u4e3b\u9898')),
                ('result', models.TextField(blank=True, help_text='Here write you solve method of this problem')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Problem.Issue')),
            ],
            options={
                'verbose_name_plural': '\u89e3\u51b3\u65b9\u6cd5',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '\u95ee\u9898\u7c7b\u522b',
            },
        ),
    ]
