# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='seq',
            field=models.CharField(default=1, max_length=10, unique=None),
            preserve_default=False,
        ),
    ]
