# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0002_issue_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='des',
            field=models.TextField(blank=True),
        ),
    ]
