# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0003_issue_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='des',
        ),
    ]
