# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0004_auto_20160415_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solve',
            name='title',
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Problem.Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solve',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Problem.Type'),
            preserve_default=False,
        ),
    ]
