######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 24 11:14:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/hello.cpp
