######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 27 15:19:21 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += gridlayout.cpp hello1.cpp hello_world.cpp
