######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 27 15:36:13 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
